# ------------------------------------------------------------
# Emulator
# ------------------------------------------------------------

# Puerto del emulador
ADB_PORT = "emulator-5554"

# Ruta del ADB (opcional, para más adelante)
ADB_PATH = "C:/LDPlayer/LDPlayer9/adb.exe"


# ------------------------------------------------------------
# Bot tuning
# ------------------------------------------------------------

DROP_RADIUS_FACTOR = 0.70  # used to calculate the drop radius based on the maximum distance from the center of the blob

# ------------------------------------------------------------
# Debug
# ------------------------------------------------------------

DEBUG = {
    "cart": True,
    "attack": True,
    "vision": True,
    "timing": True,
    "adb": False,
    "flow": True,
}

DEBUG_INSPECTION = False # used to print the file, function, and line number of the log message
# old ... DROP_ANALYZER = True # used to analyze the drop point and visualize it on the screenshot

# -----------------------------------------------------------------------------
# Drop Analyzer
# -----------------------------------------------------------------------------

# Controls which debug screenshots are generated by the Drop Analyzer.
#
# 0 = Disabled
#     No screenshots are saved.
#
# 1 = Final result
#     Saves only the final annotated screenshot.
#
# 2 = Intermediate
#     Saves the final result plus the intermediate masks used by the algorithm.
#
# 3 = Verbose
#     Saves every screenshot, including the original analysis image.
#
DROP_ANALYZER_DEBUG = 1


