# ------------------------------------------------------------
# Emulator
# ------------------------------------------------------------

# Puerto del emulador
ADB_PORT = "emulator-5554"

# Ruta del ADB (opcional, para más adelante)
ADB_PATH = "C:/LDPlayer/LDPlayer9/adb.exe"


# ------------------------------------------------------------
# Bot tuning
# ------------------------------------------------------------

DROP_RADIUS_FACTOR = 0.70  # used to calculate the drop radius based on the maximum distance from the center of the blob

# ------------------------------------------------------------
# Debug
# ------------------------------------------------------------

DEBUG_TELEGRAM = True  # Enables Telegram status messages.
TELEGRAM_STATUS_INTERVAL_MINUTES = 5

DEBUG_CATEGORIES = {
    "cart": True,
    "attack": True,
    "vision": True,
    "timing": False,
    "adb": False,
    "flow": True,
    "detection": True,
    "drop": True,
    "state": True, 
    "func": False,
}

DEBUG_INSPECTION = False # used to print the file, function, and line number of the log message
# old ... DROP_ANALYZER = True # used to analyze the drop point and visualize it on the screenshot

# Controls whether diagnostic history files are written.
# These are independent from the on-screen debug logger.
DEBUG_FILE_LOGS = {
    "drop_finder": True,
    "state_machine": True,
}

# -----------------------------------------------------------------------------
# Drop Analyzer
# -----------------------------------------------------------------------------

# Controls which debug screenshots are generated by the Drop Analyzer.
#
# 0 = Disabled
#     No screenshots are saved.
#
# 1 = Final result
#     Saves only the final annotated screenshot.
#
# 2 = Intermediate
#     Saves the final result plus the intermediate masks used by the algorithm.
#
# 3 = Verbose
#     Saves every screenshot, including the original analysis image.
#
DROP_ANALYZER_DEBUG = 1


# ------------------------------------------------------------
# Log colors
# ------------------------------------------------------------

# Colors available for log messages in the GUI.


LOG_COLORS = {
    "default": None,
    "green": "green",
    "red": "red",
    "orange": "orange",     # Debugging color for warnings and important messages.
    "blue": "blue",
    "gray": "gray",         # Debugging color for DEBUG_INSPECTION.
    "yellow": "yellow",
    "purple": "purple",
    "pink": "pink",
    "cyan": "cyan",         # Debugging color for messages that don't fit other categories.
    "magenta": "magenta",
    "brown": "brown",
    "white": "white",
    "black": "black",
}
